services:

  catalog:
    build:
      context: ./Catalog
    command: [ "npm", "run", "start" ]
    ports:
      - 8081:3000
    expose:
      - 3000
  order:
    build:
      context: ./Order
    command: [ "npm", "run", "start" ]
    ports:
      - 8082:3000
    expose:
      - 3000
  frontend:
    build:
      context: ./Frontend
    command: [ "npm", "run", "start" ]
    ports:
      - 8080:3000
    expose:
      - 3000
